### PR TITLE
Tier one

### LINKED ISSUE #52: guild generation bug
In GitLab by @epicwarrior on May 10, 2021, 15:20

the bank tends to get flooded with water and sometimes other parts of the guild when it loads up for the first time

### LINKED ISSUE #69: Being in a different dimension causes guild attack to not work properly
## Summary
If you are in another dimension such as the end or the nether and the guild attack is initiated, the reficule gateways and npcs will fail to spawn in and the guildmaster cannot follow you to the overworld.

## Steps to reproduce
Be in the nether/end, kill mobs until you trigger the attack.

## What is the current bug behaviour?
Guild attack fails to spawn in properly.

## What is the expected behaviour?
Structures should spawn in with npcs.

## Possible fixes
Force-loading overworld guild?

### LINKED ISSUE #128: Invalid Player Data
### Summary

Every time i try joining a world i made i keep getting "invalid player data"

### Steps to reproduce

i dont understand what this means

### Expected behaviour

be able to actually join a world and play on it

### Mod list

ColoredGlow Lib
Fabric API
GeckoLib
More Axolotl Variants Mod
BCLib
Bedrock Plus
Better Beacon Placement (Fabric)
BetterEnd
BetterNether
Bookshelf
Hopper+ (Better Hoppers)
HorseInBoat
Icarus
Inmis
Inventory HUD+
JamLib
Lava Clear View (Fabric)
Trinkets (Fabric)
Universal Enchants [Fabric]
Visual Workbench [Fabric]
Waystones (Fabric Edition)
WI Zoom
WMITAF
XP From Crops (Fabric)

### Possible fixes

_No response_

### Relevent logs and/or screenshots/videos

_No response_

### Other

_No response_

### LINKED ISSUE #136: Convert Crowdin translation files before 1.0.4 release
Currently translation files have the wrong key, Minecraft expects them to all be lowercase, but Crowdin has them such as `en_US.json`. This is wrong and we need to manually fix all of these.

### PR DESCRIPTION
**Pull request by SamB440**
Adds most of the features of tier 1 from the original mod.

Also adds some new things.

Converting villagers into workers is missing because they are very complicated to code.

Closes #136, closes #69, closes #52, closes #128

todo:

- [x] Re-enable "keep distance from guild" with citybuilder
- [x] Remove debug statements

### CODE REVIEW

File: src/main/java/com/convallyria/taleofkingdoms/server/packet/outgoing/OutgoingInstanceSyncPacketHandler.java [hunk 1]
```diff
@@ -1,45 +1,33 @@
...
-            passedData.writeInt(instance.getCoins(player.getUuid()));
-            passedData.writeInt(instance.getWorthiness(player.getUuid()));
-            passedData.writeLong(instance.getFarmerLastBread(player.getUuid()));
-            passedData.writeBoolean(instance.hasContract(player.getUuid()));
-            passedData.writeBoolean(instance.isLoaded());
-            passedData.writeBlockPos(instance.getStart());
-            passedData.writeBlockPos(instance.getEnd());
-            passedData.writeBlockPos(instance.getOrigin());
-            instance.getHunterUUIDs().forEach((playerUuid, hunterUuids) -> hunterUuids.forEach(passedData::writeUuid));
+            passedData.encodeAsJson(ConquestInstance.CODEC, instance);
```
Comment (SamB440) [inline src/main/java/com/convallyria/taleofkingdoms/server/packet/outgoing/OutgoingInstanceSyncPacketHandler.java:30]: We are leaking other player's conquest data here

File: src/main/java/com/convallyria/taleofkingdoms/client/gui/entity/citybuilder/CityBuilderTierOneGui.java [hunk 2]
```diff
@@ -0,0 +1,209 @@
...
+                MinecraftClient.getInstance().setScreen(new CityBuilderPriceListGui(player, entity, instance));
+            }).positioning(Positioning.relative(80, 80)).sizing(Sizing.fixed(100), Sizing.fixed(20))
+        );
+
+        // Actually starts at 70, first has addition of +20
+        int currentY = 15;
+        int currentX = 10;
+        final int maxPerRow = 7;
+        int currentRow = 0;
+        for (BuildCosts build : BuildCosts.values()) {
```
Comment (SamB440) [inline src/main/java/com/convallyria/taleofkingdoms/client/gui/entity/citybuilder/CityBuilderTierOneGui.java:156]: What happens if the player tries to build something that's for tier 2+? need to disable invalid tier builds
